### ISSUE TITLE
StatsModels.Formula error with julia_setup()

### ISSUE THREAD

**Issue by jjlynch2** [Non-Contradiction/JuliaCall#108]
After updating my Julia version to 1.1.1, calling julia_setup() produces an error message. This is happening with R 3.6.0 on a Linux platform.

    library(JuliaCall)
    julia_setup()
    Julia version 1.1.1 at location /usr/bin will be used.
    Loading setup script for JuliaCall...
    WARNING: replacing module JuliaCall.
    WARNING: could not import StatsModels.Formula into RCall
    ERROR: LoadError: LoadError: UndefVarError: Formula not defined

**Comment by Non-Contradiction** [comment]
Thanks for the feedback.

Julia v1.1 worked on my mac but broke after a `Pkg.update()` in Julia.

The issue seems to be caused by updates in `StatsModels.jl`, which is a JuliaCall's dependency.
For example, RCall is a dependency for JuliaCall, and similar error will happen with `using RCall` in Julia.
Setting `StatsModels.jl` to an old version can temporarily solve the problem as follows:
Type `]` in Julia to enter pkg mode, and 
```
(v1.1) pkg> add StatsModels@0.5
 Resolving package versions...
  Updating `~/.julia/environments/v1.1/Project.toml`
  [3eaba693] + StatsModels v0.5.0
  Updating `~/.julia/environments/v1.1/Manifest.toml`
  [4fba245c] - ArrayInterface v0.1.1
  [6fe1bfb0] - OffsetArrays v0.11.1
  [731186ca] - RecursiveArrayTools v0.20.0
  [1277b4bf] - ShiftedArrays v0.5.0
  [3eaba693] ↓ StatsModels v0.6.0 ⇒ v0.5.0
```

**Comment by Non-Contradiction** [comment]
Corresponding `RCall.jl` issue is at: https://github.com/JuliaInterop/RCall.jl/issues/306

**Comment by jjlynch2** [comment]
Thanks for that. Switching StatsModels back to 0.5.0 has my apps working again.
