### ISSUE TITLE
JuliaCall still maitained?

### ISSUE THREAD

**Issue by instantkaffee** [Non-Contradiction/JuliaCall#137]
I have JuliaCall in productive use and so far its a great value-add to interface between R and the great JuMP framework for optimization.

I am concerned about the fact that there are open Github issues reaching back to 2017!

Therefore the question: is JuliaCall still activly maintained?

Take no offence, Thx

**Comment by Non-Contradiction** [comment]
Glad to hear that JuliaCall is in productive use for you! And welcome for questions/feedbacks for JuliaCall!

Well, JuliaCall is quite actively maintained, and it is used (nearly) everyday by myself. 

Due to the evolution of Julia, JuliaCall, and ecosystems, some issues may not be of relevance currently.
Also, some solved issues may not be closed in a timely manner, etc.
There are also some issues that are hard to solve. I sometimes go back to see if there is any way to deal with them. But, ......, they are just hard to solve.

BTW, Julia itself has open issues back to 2011, so I don't think old open issues is a problem in general.
