### ISSUE TITLE
Julia Queryverse commands not working in code chunks

### ISSUE THREAD

**Issue by rleyvasal** [Non-Contradiction/JuliaCall#163]
Julia Queryverse commands return an error message. 

The last line in the following code fails in RStudio inside a code chunk. (same code runs without a problem in a Jupyter notebook)

using Queryverse, VegaDatasets
cars = dataset("cars")
cars |> @groupby(_.Origin) |> @map(key(\_))
![julia_queryverse](https://user-images.githubusercontent.com/61335136/111085835-68bcbf00-84d6-11eb-85df-55d62360e122.PNG)
![julia_queryverse_2](https://user-images.githubusercontent.com/61335136/111085837-69555580-84d6-11eb-9dbb-0c6706a8dadc.PNG)

**Comment by Non-Contradiction** [comment]
Thank you very much for the feedback!

I can reproduce the same error in RStudio notebook. It seems that the problem is with the display system. The following works for me. Note that for the third chunk, a comma is added at the end of the command to suppress the displaying of the output. And in the fourth code chunk, the same result is displayed without any problem. But I don't understand why this fix the issue (at least for me), and need some further check into this. I guess that there may be some "magic trick" behind Queryverse, which doesn't play well with JuliaCall.

    ```{julia}
    using Queryverse, VegaDatasets
    ```

    ```{julia}
    cars = dataset("cars")
    ```
    
    ```{julia}
    result = cars |> @groupby(_.Origin) |> @map(key(_));
    ```
    
    ```{julia}
    result
    ```

By the way, I suggest to quote the code in the GitHub issue, and provide the code for the code chunk beyond the screenshot. A simple way to quote the code is to use the function provided in the GitHub editor. Another way is that you can select the code, and then press Tab two times.

**Comment by Non-Contradiction** [comment]
I just push a commit which fixes the issue on my laptop. Would you mind trying out to see if it works? Thanks!

**Comment by rleyvasal** [comment]
The code you provided works.

Thanks for the feedback about quoting the code. I will do that in the future.
