### ISSUE TITLE
print() prints nothing in R Markdown

### ISSUE THREAD

**Issue by yutannihilation** [Non-Contradiction/JuliaCall#26]
I found this code chunk won't return any output:

    ```{julia}
    print(1)
    ```

Isn't this a bug? Or an usual behaviour of `print()`? Sorry, I'm totally a newbie to Julia...

**Comment by Non-Contradiction** [comment]
Thank you for the feedback.

Currently JuliaCall doesn't capture the std output of julia, and `print` prints to std output, which is the reason of this behaviour. 

Is there a reason not to use

    ```{julia}
    1
    ```
instead of `print`? 

I think this one is more julia-idiomatic. And the output will be typically similar to `print`.

**Comment by yutannihilation** [comment]
Thanks for the clear explanation! No, there are no reason except that I was just curious :)

I'll try to get used to julia-idiomatic way. Thank you for this great package anyway.
