### ISSUE TITLE
Consider using stopifnot

### ISSUE THREAD

**Issue by dmbates** [Non-Contradiction/JuliaCall#35]
I noticed that your code has sections like
```r
    if (!(length(func_name) == 1 && is.character(func_name))) {
        stop("func_name should be a character scalar.")
    }
    if (!(is.list(arg_list))) {
        stop("arg_list should be the list of arguments.")
    }
    if (!(length(show_value) == 1 && is.logical(show_value))) {
        stop("show_value should be a logical scalar.")
    }
```
The `stopifnot` function was created so you can collapse that to
```r
   stopifnot(length(func_name) == 1, is.character(func_name), is.list(arg_list), 
       length(show_value) == 1, is.logical(show_value))
```

**Comment by Non-Contradiction** [comment]
I used this at the first place because that it can provide a clear error message.
Originally I kind of think that I would export this function.
But since the function is used completely internally for now if I remember correctly, it is okay to collapse the code.
Would you create a PR for this? Or I can deal with it later after solving other issues.

**Comment by Non-Contradiction** [comment]
I found the message from `stopifnot` is already good enough.
Thank you for the suggestion!
