### ISSUE TITLE
Composite types and call-overloading

### ISSUE THREAD

**Issue by ChrisRackauckas** [Non-Contradiction/JuliaCall#49]
I would like to see if I could get full compatibility with the `ODESolution` object of DifferentialEquations.jl. Right now diffeqr is avoiding this by returning a list of two arrays from that solution object. However, it would be better if it could return that full type. Is there a way to define auto-wrapper types for Julia types to have the same fields in an R object?

Additionally, this type has call-overloading so that way `sol(t)` is an interpolation. Is there a way to keep these function overloads in whatever auto-wrapper type?

**Comment by Non-Contradiction** [comment]
1. Normally, when `JuliaCall` encounters the types it doesn't know about beyond the common types like float64 vectors, matrices...., it will try to return a simple wrapper of `JuliaObject` to R, and for the `JuliaObject`, there is some functions to get access to the fields.

2. But currently 1 is not available to `ODEsolution` and I find that it is because `ODEsolution  <: AbstractArray` and the first type signature for a solution in `Float64` is `Float64`, so `JuliaCall` and `RCall.jl` mistake `ODEsolution` for a Float64 vector and automatically convert it to a Float64 vector. 
This type of mistakes could lead to other errors and I need to think on it further.

3. And no auto-wrapper is available, but I think it is possible to quickly wrap up a function to provide the basic functionality. I will think on how to do it and come up a solution in a few days hopefully.

4. And there are several ways to deal with the problem and provide a wrapper for `ODEsolution` but not automatically. The first is to code a function on the Julia side to map the `ODEsolution` to julia dictionary, and then `JuliaCall` knows what to do. The second way is to follow the `RCall.jl`'s documentation on converting custom types: <http://juliainterop.github.io/RCall.jl/stable/custom.html>.

**Comment by Non-Contradiction** [comment]
Due to the issue previously mentioned, `JuliaObject` is not used for `ODESolution`. If the `JuliaObject` wrapper is forced to be used for `ODESolution`, we have:
```
library(JuliaCall)
julia_setup()
julia_command("using OrdinaryDiffEq")
f <- function(u,p,t) 1.01*u
u0 <- 1/2
tspan <- list(0.0, 1.0)
class(tspan) <- "JuliaTuple"
prob <- julia_call("ODEProblem", f, u0, tspan)
julia_command("@eval JuliaCall @suppress_err begin sexp(x :: Main.ODESolution) = sexp(JuliaObject(x)) end;")
sol <- julia_call("solve", prob, julia_eval("Tsit5()"))
sol

#Julia Object of type
#DiffEqBase.ODESolution{Float64,1,Array{Float64,1},Void,Void,Array{Float64,1},Array{Array{Float64,1},#1},DiffEqBase.ODEProblem{Float64,Float64,false,Void,RCall.##33#34{Ptr{RCall.ClosSxp}},Void,Void,#UniformScaling{Int64},DiffEqBase.StandardODEProblem},OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Interpol#ationData{RCall.##33#34{Ptr{RCall.ClosSxp}},Array{Float64,1},Array{Float64,1},Array{Array{Float64,1#},1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}.
#retcode: Success
#Interpolation: specialized 4th order "free" interpolation
#t: [0.0, 0.0996426, 0.345703, 0.677692, 1.0]
#u: [0.5, 0.552939, 0.708938, 0.99136, 1.3728]

field(sol, "u")
# [1] 0.5000000 0.5529387 0.7089381 0.9913596 1.3728004
field(sol, "t")
# [1] 0.00000000 0.09964259 0.34570306 0.67769232 1.00000000
```

It's not ideal, but could be adjusted for a better wrapper.

**Comment by Non-Contradiction** [comment]
I just add a convenient method to `JuliaObject`, so things like `sol$u`, `sol$t`, $sol$retcode` and etc could be used.
```
library(JuliaCall)
julia_setup()
julia_command("using OrdinaryDiffEq")
f <- function(u,p,t) 1.01*u
u0 <- 1/2
tspan <- list(0.0, 1.0)
class(tspan) <- "JuliaTuple"
prob <- julia_call("ODEProblem", f, u0, tspan)
julia_command("@eval JuliaCall @suppress_err begin sexp(x :: Main.ODESolution) = sexp(JuliaObject(x)) end;")
sol <- julia_call("solve", prob, julia_eval("Tsit5()"))
sol

fields(sol)

field(sol, "u")
field(sol, "t")
## field of JuliaObject could also get with x$name
sol$u
sol$t
sol$retcode
```
Currently one limitation is although `sol$u` is possible, but R doesn't know about this and it has to lookup in julia dynamically, so if you type `sol$` in IDE like RStudio, it will not give you hints about `sol$u`.
And a general way to do automatic call-overloading is quite hard.
These two limitations exist because `JuliaObject` is only a simple wrapper, it will be too much overhead to lookup all the fields when creating `JuliaObject` and the same thing applies to automatic call-overloading.

I have an idea to solve the limitation and allow the automatic overloading to some extent.
Maybe I could add something into `JuliaCall` like this:
```
autoWrap("ODESolution", fields = c("u", "t", "retcode"), methods = c("solve", "interp"))
```
And then 
1. `ODESolution` will be converted to a similar type to `JuliaObject` when needed.
2. The fields of `u`, `t` and `retcode` will be added to the object `sol` (if `fields` is not given, then all the fields of `ODESolution` will be wrapped) and R will know their existence.
3. And functions like `sol$solve(...)` and `sol$interp(...)` will call `solve(sol, ...)` and `interp(sol, ...)` in julia, and if `methods` is not given, then no there will be no overloading except the most basic ones.

@ChrisRackauckas Do you think this is a good idea? Any suggestions?

**Comment by ChrisRackauckas** [comment]
autowrap sounds like a great idea. I guess we'll need to write a function that forwards the interpolation, and `sol$interp(t)` isn't that bad of a syntax.

**Comment by Non-Contradiction** [comment]
An initial implementation of `autowrap` is in the master of `JuliaCall`.
An example is:
```
library(JuliaCall)
julia_setup()
julia_command("using OrdinaryDiffEq")
f <- function(u,p,t) 1.01*u
u0 <- 1/2
tspan <- list(0.0, 1.0)
class(tspan) <- "JuliaTuple"
prob <- julia_call("ODEProblem", f, u0, tspan)
# julia_command("@eval JuliaCall @suppress_err begin sexp(x :: Main.ODESolution) = sexp(JuliaObject(x)) end;")
autowrap("ODESolution", fields = c("u", "t"))
sol <- julia_call("solve", prob, julia_eval("Tsit5()"))
sol
sol$u
sol$t
```

**Comment by ChrisRackauckas** [comment]
Cool thanks! I'll make use of this in diffeqr and let you know if I run into any issues.

BTW, I see that you got a GSoC in the R org for this connection to autodiff. I find it awesome that the autodiff through R works. We're making use of it in the stiff solvers, like `Rosenbrock23()` and `Rodas5()`, and it was cool to see that it worked. A higher order test would be getting something like our parameter estimation tooling wrapped (http://docs.juliadiffeq.org/latest/analysis/parameter_estimation.html ). I'd be willing to help you setup diffeq-related examples if you're interested, and helping work through any of the issues on the diffeq side.

**Comment by Non-Contradiction** [comment]
You are welcome.
And it will be great to have diffeq-related examples for the autodiff package I'm going to create. Thank you very much!
