### ISSUE TITLE
Using rice, JuliaCall and PyCall together cause segfault.

### ISSUE THREAD

**Issue by Non-Contradiction** [Non-Contradiction/JuliaCall#6]
@randy3k 

Maybe here is a better place to discuss the problem.

When I have segfault, the last lines of error look like this:

    signal (11): Segmentation fault: 11
    while loading no file, in expression starting on line 0
    tupledealloc at /anaconda/lib/libpython3.6m.dylib (unknown line)
    code_dealloc at /anaconda/lib/libpython3.6m.dylib (unknown line)
    pydecref at /Users/lichangcheng/.julia/v0.6/PyCall/src/PyCall.jl:96
    unknown function (ip: 0x11eb0a2e2)

I think this should be reproduced by 

    Python -> import julia -> julia -> using PyCall -> exit julia

But to my surprise, when I exit julia in pyjulia, python ends as well as julia.

**Comment by Non-Contradiction** [comment]
If I use

    R -> reticulate -> Python -> import julia -> julia -> using PyCall -> exit julia

R, python, julia will all end.

**Comment by randy3k** [comment]
I guess we also need to consider the [Rf_endEmbeddedR](https://github.com/JuliaInterop/RCall.jl/blob/dd11f23a8bcc0b6af0e7e76e29f559bce0e457ae/src/setup.jl#L205-L205) of RCall.

**Comment by randy3k** [comment]
I confirm that it is related to `Rf_endEmbeddedR`. There is segfault when that is disabled.

**Comment by Non-Contradiction** [comment]
Really? When using JuliaCall, since there is an R exist already, `Rembedded[]` should be false?

**Comment by randy3k** [comment]
I forgot to load `PyCall`..forget what I have said.

**Comment by randy3k** [comment]
The `exit()` command of julia will [end](https://github.com/JuliaLang/julia/blob/d989d3e79b0712e0ab2ed74cd7c3929c39ac7911/src/jl_uv.c#L550) the whole current process, so it will also end `python` when `pyjulia` is used.

**Comment by randy3k** [comment]
Actually, it might be incorrect to call the `exit()` command when Julia is embedded in other processes because it might ends the R process too early (just imagine there is more than one finalizer).

**Comment by randy3k** [comment]
As for the reason of segfault, my theory is that the PyObject created are already being GC'ed by the  python, so the `pydecref` is trying to access a non-existing memory when `exit()` is called.

**Comment by randy3k** [comment]
And oddly, `using PyCall` works peacefully with python 2.7.

```
(py27) (rmbpro)-~$ rice --version
rice version: 0.0.27-dev
python version: 2.7.13
python executable: /Users/Randy/miniconda3/envs/py27/bin/python

(py27) (rmbpro)-~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> ENV["PYTHON"] = "/Users/Randy/miniconda3/envs/py27/bin/python"
"/Users/Randy/miniconda3/envs/py27/bin/python"

julia> Pkg.build("PyCall")
INFO: Building Conda
INFO: Building PyCall
INFO: PyCall is using /Users/Randy/miniconda3/envs/py27/bin/python (Python 2.7.13) at /Users/Randy/miniconda3/envs/py27/bin/python, libpython = /Users/Randy/miniconda3/envs/py27/lib/libpython2.7
INFO: /Users/Randy/.julia/v0.6/PyCall/deps/deps.jl has been updated
INFO: /Users/Randy/.julia/v0.6/PyCall/deps/PYTHON has been updated
julia> using PyCall
INFO: Precompiling module PyCall.

(py27) (rmbpro)-~$ rice
R version 3.4.1 (2017-06-30) -- Single Candle
Platform: x86_64-apple-darwin16.7.0

r$> library(JuliaCall)

r$> julia <- julia_setup()
Julia at location /Applications/Julia-0.6.app/Contents/Resources/julia/bin will be used.
Julia version 0.6.0 found.
Julia initiation...
Finish Julia initiation.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.

r$> julia$eval_string("using PyCall")
NULL

r$>

Julia exit.
```

**Comment by randy3k** [comment]
My suggestion is to not call `exit()` manually and let the R process to close all the resources. Is there any reason you have to call `exit()` explicitly?

**Comment by Non-Contradiction** [comment]
My previous impression is that call `exit()` explicitly can ensure that Julia runs all the finalizers that should be run. For example, in the embedding manual of julia <https://docs.julialang.org/en/stable/manual/embedding/>, there is this code chunk in the example of using c code to embed julia directly:

    /* strongly recommended: notify Julia that the
             program is about to terminate. this allows
             Julia time to cleanup pending write requests
             and run all finalizers
    */
    jl_atexit_hook(0);
    return 0;

I think maybe I should try to call the c code `jl_atexit_hook(0);` instead of calling `exit()` from julia directly.

**Comment by Non-Contradiction** [comment]
I just do a quick check, if I do nothing at exiting, the exitting hooks in julia (sometimes necessary) won't be called. But I also shouldn't call `exit()` directly from julia. So I think I should call the c function to `jl_atexit_hook(0)` to activate the hooks and let other processes to take care of the resources.

**Comment by randy3k** [comment]
I also confirm that that pyjulia does not execute `jl_atexit_hook` when it quits. Therefore, we are not seeing segfaults when `pyjulia` quits. I expect a similar segfault would appear if `pyjulia` runs `jl_atexit_hook` when it quits.

**Comment by Non-Contradiction** [comment]
Yes, I just find that the `jl_atexit_hook` can also cause segfault too. And doing nothing at quitting julia is okay. But I'm not sure if there could be any possible problems like memory leak caused by not calling `jl_atexit_hook`.

**Comment by randy3k** [comment]
Maybe a dirty fix, for now, is to not call the exit hooks when `rice` is in use. It would be detected by checking the environmental variable `Sys.getenv("RICE_VERSION")`. I need to go more researches on this issue.

By the way, is the master branch usable? I try updating to the latest JuliaCall, but it gives me the following error.
The cran version is working fine for me.

<details>
(rmbpro)-~$ R -q -e "JuliaCall::julia_setup()"
> JuliaCall::julia_setup()
ERROR: could not open file /usr/local/share/julia/julia-config.jl
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:305
 [4] _start() at ./client.jl:371
ERROR: could not open file /usr/local/share/julia/julia-config.jl
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:305
 [4] _start() at ./client.jl:371
ERROR: could not open file /usr/local/share/julia/julia-config.jl
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:569
 [2] include(::String) at ./sysimg.jl:14
 [3] process_options(::Base.JLOptions) at ./client.jl:305
 [4] _start() at ./client.jl:371
file8b5c52004199.cpp:12:14: fatal error: 'julia.h' file not found
    #include <julia.h>
             ^
1 error generated.
make: *** [file8b5c52004199.o] Error 1

ERROR(s) during compilation: source code errors or compiler configuration errors!

Program source:
  1: #include <R.h>
  2: #include <Rdefines.h>
  3: #include <R_ext/Error.h>
  4:
  5:
  6:     // Taken from http://tolstoy.newcastle.edu.au/R/e2/devel/06/11/1242.html
  7:     // Undefine the Realloc macro, which is defined by both R and by Windows stuff
  8:     #undef Realloc
  9:     // Also need to undefine the Free macro
 10:     #undef Free
 11:
 12:     #include <julia.h>
 13:
 14:
 15: extern "C" {
 16:   SEXP file8b5c52004199 (  );
 17: }
 18:
 19: SEXP file8b5c52004199 (  ) {
 20: jl_init(); return R_NilValue;
 21:   warning("your C program does not return anything!");
 22:   return R_NilValue;
 23: }
Error in compilation.
Maybe this is because the compiler version is too old.
You should use GCC version 4.7 or later on Linux, or Clang version 3.1 or later on Mac.
Error in compileCode(f, code, language, verbose) :
  Compilation ERROR, function(s)/method(s) not created! file8b5c52004199.cpp:12:14: fatal error: 'julia.h' file not found
    #include <julia.h>
             ^
1 error generated.
make: *** [file8b5c52004199.o] Error 1
Calls: <Anonymous> ... <Anonymous> -> withCallingHandlers -> <Anonymous> -> compileCode
In addition: Warning messages:
1: running command '/usr/local/bin/julia /usr/local/share/julia/julia-config.jl --cflags' had status 1
2: running command '/usr/local/bin/julia /usr/local/share/julia/julia-config.jl --ldflags' had status 1
3: running command '/usr/local/bin/julia /usr/local/share/julia/julia-config.jl --ldlibs' had status 1
4: running command '/usr/local/Cellar/r/3.4.1_2/lib/R/bin/R CMD SHLIB file8b5c52004199.cpp 2> file8b5c52004199.cpp.err.txt' had status 1
Execution halted
</details>

**Comment by randy3k** [comment]
Oh, I see what causes the issue, will submit a PR soon.

**Comment by randy3k** [comment]
Another strange discovery,

If I run `using PyCall` via `julia_console()`, there will be no segfault.

**Comment by randy3k** [comment]
I got a theory, it may be related to the `ans` variable which saves the last value.

**Comment by randy3k** [comment]
Maybe to solution is to perform manual garbage collection before exiting julia: `gc(); exit()`

It seems to have fixed the issue for me.

**Comment by Non-Contradiction** [comment]
`gc()` doesn't work for me, but the fact of entering `julia_console()` itself works for me. Entering `julia_console()`, doing nothing and quit the console. Then the segfault go away. Maybe I miss something in the startup of JuliaCall, I should really check this.

**Comment by randy3k** [comment]
That's even stranger. This works for me.

```
Platform: x86_64-apple-darwin16.7.0

r$> library(JuliaCall)

r$> julia_command("using PyCall")

r$> julia_command("gc()")

r$>

Julia exit.
```

**Comment by Non-Contradiction** [comment]
Okay, I see. A random `julia_command` will solve the issue, doesn't need to be `gc()`.

**Comment by Non-Contradiction** [comment]
So there is some quick solution for the issue, just do something like `julia_command("1")` before exiting, but still doesn't know the real issue, and by the way, `.julia$cmd("1");` doesn't solve the issue.

**Comment by randy3k** [comment]
> `.julia$cmd("1");` doesn't solve the issue.

this is a piece of valuable information.

**Comment by Non-Contradiction** [comment]
In fact, `julia_command("1;") ` doesn't work, `julia_command("1")` does, so there might be some problems in my implementation of JuliaCall display system?

**Comment by randy3k** [comment]
But a bug in the display system doesn't explain why `julia_command("using PyCall; 1")` doesn't work.

**Comment by randy3k** [comment]
Finally, I understand why it happens. It is because some python memory is being gc'ed in the rice [clean up process](https://github.com/randy3k/rice/blob/0f8be78ab634d5d4d7ee14770973808a1aaa4062/rice/session.py#L173-L173) and PyCall will then later gc the same memory and causes the segfault.

However, I have no idea what that memory is about. Our experiment above suggests that the memory is related to the last expression being evaluated.

**Comment by randy3k** [comment]
after some more digging, I finally have fixed it. It is actually an issue of rice.
this should be fixed by https://github.com/randy3k/rice/commit/546b49b7bc12a59076ee98a897f19d72b3051eae

**Comment by Non-Contradiction** [comment]
Great! Since the problem is gone, this issue can be closed.
