### ISSUE TITLE
julia_setup() not working with R 3.5.1 and Julia 1.0

### ISSUE THREAD

**Issue by sjmgarnier** [Non-Contradiction/JuliaCall#61]
The following error message appears when running julia_setup() with R 3.5.1 and Julia 1.0. 

> Julia version 1.0.0 at location /opt/julia/bin will be used.
Loading setup script for JuliaCall...
ERROR: LoadError: LoadError: UndefVarError: endof not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at ./sysimg.jl:13
 [2] top-level scope at none:0
 [3] include at ./boot.jl:317 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1038
 [5] include at ./sysimg.jl:29 [inlined]
 [6] include(::String) at /home/simon/.julia/packages/AxisArrays/uZ7JS/src/AxisArrays.jl:3
 [7] top-level scope at none:0
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/simon/.julia/packages/AxisArrays/uZ7JS/src/core.jl:59
in expression starting at /home/simon/.julia/packages/AxisArrays/uZ7JS/src/AxisArrays.jl:18
ERROR: LoadError: Failed to precompile AxisArrays [39de3d68-74b9-583c-8d2d-e117c070f3a9] to /home/simon/.julia/compiled/v1.0/AxisArrays/zm48T.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1184
 [4] _require(::Base.PkgId) at ./logging.jl:311
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
 [8] include at ./boot.jl:317 [inlined]
 [9] include_relative(::Module, ::String) at ./loading.jl:1038
 [10] include(::Module, ::String) at ./sysimg.jl:29
 [11] top-level scope at none:2
 [12] eval at ./boot.jl:319 [inlined]
 [13] eval(::Expr) at ./client.jl:389
 [14] top-level scope at ./none:3
in expression starting at /home/simon/.julia/packages/RCall/6RPqA/src/RCall.jl:11
LoadError("/home/simon/R/x86_64-pc-linux-gnu-library/3.5/JuliaCall/julia/setup.jl", 62, ErrorException("Failed to precompile RCall [6f49c342-dc21-5d91-9882-a32aef131414] to /home/simon/.julia/compiled/v1.0/RCall/8GFyb.ji.")) Error in .julia$cmd(paste0("Base.include(Main,\"", system.file("julia/setup.jl",  : 
  Error happens when you try to execute command Base.include(Main,"/home/simon/R/x86_64-pc-linux-gnu-library/3.5/JuliaCall/julia/setup.jl") in Julia.
                        To have more helpful error messages,
                        you could considering running the command in Julia directly
In addition: Warning message:
In system2(file.path(.julia$bin_dir, "julia"), shQuote(command),  :
  running command ''/opt/julia/bin/julia' '/home/simon/R/x86_64-pc-linux-gnu-library/3.5/JuliaCall/julia/install_dependency.jl' '/usr/lib/R' 2>&1' had status 1

**Comment by randy3k** [comment]
Unfortunately, AxisArrays.jl is bloking `RCall.jl` which means JuliaCall is not yet working on julia v1.0.

**Comment by Non-Contradiction** [comment]
Yes, as Randy said, JuliaCall has some julia package dependencies, and `AxisArrays.jl` is one of them which doesn't work on julia v1.0 yet, so is JuliaCall. 

But JuliaCall's main functionality should work with julia v0.7 (which is actually the same with julia v1.0 except julia v1.0 treats deprecation warnings as errors) if you use the latest CRAN version (with few deprecation warnings from JuliaCall itself) or the github master (with no deprecation warning from JuliaCall itself).

**Comment by randy3k** [comment]
Btw, there is a plan of temporarily dropping AxisArrays. 
see https://github.com/JuliaInterop/RCall.jl/pull/257#issuecomment-412614766 and https://github.com/JuliaLang/METADATA.jl/pull/16594#issuecomment-412503646

**Comment by Non-Contradiction** [comment]
With the github version of `JuliaCall`, it should be possible to use it with `Julia v1.0`.

**Comment by sjmgarnier** [comment]
Nice!

**Comment by sjmgarnier** [comment]
Not sure is related, but now I get the following error when trying to source a .jl file

> julia_source("test.jl")
Error: Error happens in Julia.
UndefVarError: include not defined
Stacktrace:
 [1] funcfind(::String) at /usr/local/lib/R/3.5/site-library/JuliaCall/julia/setup.jl:102
 [2] docall(::Ptr{Nothing}) at /usr/local/lib/R/3.5/site-library/JuliaCall/julia/setup.jl:156

**Comment by Non-Contradiction** [comment]
Thank you for providing feedback!
It's caused by the change in `include` function of `Julia`.
I opened a separate issue #65. And will fix it very soon.

**Comment by AsadiMarziehAF** [comment]
Hey,
I need to specify the full path to the Julia software on my computer and connect Julia to R. but I have been getting errors. The following text is the code that I used and the problem that occurred. Does anybody know how can I fix that?
Thank you so much
Marzieh

    setwd("C:/Users/ASADI/Desktop/R")
    library(ResistanceGA)
    Loading required package: raster
    Loading required package: sp
    Registered S3 method overwritten by 'spatstat':
    method from
    print.boxx cli
    Warning message:
    replacing previous import ‘lme4::getData’ by ‘raster::getData’ when loading ‘ResistanceGA’
    JULIA_HOME <- "C:/Users/ASADI/AppData/Local/Julia-1.3.1/bin/"
    JuliaCall::julia_setup(JULIA_HOME)
    Julia version 1.3.1 at location C:\Users\ASADI\AppData\Local\JULIA-1.1\bin will be used.
    Loading setup script for JuliaCall...
    Error in .julia$cmd(paste0("Base.include(Main,"", system.file("julia/setup.jl", :
    Error happens when you try to execute command Base.include(Main,"C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/setup.jl") in Julia.
    To have more helpful error messages,
    you could considering running the command in Julia directly
    In addition: Warning message:
    In system2(file.path(.julia$bin_dir, "julia"), shQuote(command), :
    running command '"C:\Users\ASADI\AppData\Local\JULIA-1.1\bin/julia" "--startup-file=no" "C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/install_dependency.jl" "C:/PROGRA1/R/R-401.3"' had status 1
    Untitled
![1](https://user-images.githubusercontent.com/57016053/107678404-9a145600-6cb0-11eb-90bd-d8c087a21c79.png)

**Comment by Non-Contradiction** [comment]
@AsadiMarziehAF I think the problem is a separate issue. I suggest we open a separate issue on this one. 
And could you check the following in julia to see what the error actually is?
```
ENV["R_HOME"]="the path you get in R from R.home()"
Base.include(Main,"C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/setup.jl")
```

**Comment by AsadiMarziehAF** [comment]
Hey, Changcheng Li 
Thank you so much for the reply, I used the code below to execute the command in Julia but I have been getting errors. The following pic is the code I used and the problem that occurred.
Thanks

ENV["R_HOME"]="the path you get in R from R.home()"
Base.include(Main,"C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/setup.jl")

![julia](https://user-images.githubusercontent.com/57016053/107888774-ba981680-6f23-11eb-8678-6b360fa8ce7c.png)

**Comment by Non-Contradiction** [comment]
Sorry if I didn't make myself clear. But `ENV["R_HOME"]="the path you get in R from R.home()"` means that first run `R.home()` in R, and copy paste the path you get into `ENV["R_HOME"]="the path you get in R from R.home()"`, and then run `Base.include(Main,"C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/setup.jl")`. And you are more than welcome to open a separate issue on this because it is a separate one.

**Comment by AsadiMarziehAF** [comment]
Hey, Changcheng Li
Thank you so much for the reply, I used the code below to execute the command in R but I have been getting errors. 
Thanks

> setwd("C:/Users/ASADI/Desktop/R")
> R.home()
[1] "C:/PROGRA~1/R/R-40~1.3"
> ENV["R_HOME"]="the path you get in R from R.home(C:/PROGRA~1/R/R-40~1.3)"
Error in ENV["R_HOME"] = "the path you get in R from R.home(C:/PROGRA~1/R/R-40~1.3)" : 
  object 'ENV' not found

![R 1](https://user-images.githubusercontent.com/57016053/107983917-09a18280-6fdc-11eb-98c0-1c2444d90c11.png)

**Comment by Non-Contradiction** [comment]
@AsadiMarziehAF What you should do is in Julia
```
ENV["R_HOME"]="C:/PROGRA~1/R/R-40~1. 3"
Base.include(Main,"C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/setup.jl")
```

**Comment by AsadiMarziehAF** [comment]
Hi, Changcheng Li
Thank you so much for helping me, I used the code below in Julia but I have been getting errors.
Thanks
![julia](https://user-images.githubusercontent.com/57016053/108261260-a13bd800-7178-11eb-8586-8c86c48b1621.png)

**Comment by Non-Contradiction** [comment]
@AsadiMarziehAF Looks like we finally knows where the problem is! A google search gives me many results. I think <https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/527> and <https://discourse.julialang.org/t/cant-install-openspecfun-jll/33593> are relevant. It seems that the problem is caused by some setting with internet connection software. Would you see if the information in the links solves the issue? If these information in the links are not solving the issue, then you may post further questions in the links.
By the way, it is generally more helpful to copy and paste error information instead of screenshot. So people can search the issue/try your code more conveniently.

**Comment by AsadiMarziehAF** [comment]
Hi, Changcheng Li
Thank you so much.
I will try to solve this problem.

**Comment by AsadiMarziehAF** [comment]
Hi, Changcheng Li
I read and tried the messages on JuliaPackaging/BinaryBuilder.jl#527 and https://discourse.julialang.org/t/cant-install-openspecfun-jll/33593  but I couldn't install 'OpenSpecFun'. 
I tried to reinstall Julia according to the method  (https://discourse.julialang.org/t/cant-install-openspecfun-jll/33593 ) but I couldn't fix my problem.
If you have any ideas, please let me know.
Thanks
Marzieh

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> ENV["R_HOME"]="C:/PROGRA~1/R/R-40~1. 3"
"C:/PROGRA~1/R/R-40~1. 3"

julia> Base.include(Main,"C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/j
ulia/setup.jl")
ERROR: LoadError: ArgumentError: Package RCall not found in current path:
- Run `import Pkg; Pkg.add("RCall")` to install the RCall package.

Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:893
 [2] include(::Function, ::Module, ::String) at .\Base.jl:380
 [3] include(::Module, ::String) at .\Base.jl:368
 [4] top-level scope at REPL[2]:1
in expression starting at C:\Users\ASADI\Documents\R\win-library\4.0\JuliaCall\j
ulia\setup.jl:72

julia> import Pkg;

julia> Pkg.add("RCall")
   Updating registry at `C:\Users\ASADI\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Downloading artifact: OpenSpecFun
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.
SecurityProtocolType" due to invalid enumeration values. Specify one of the fol
lowing enumeration values and try again. The possible enumeration values are "S
sl3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "The underlying connecti
on was closed: An unexpected error occurred on a send."
At line:12 char:24
+ $webclient.DownloadFile <<<< ("https://pkg.julialang.org/artifact/e6e3e56185c
a54f071864e989e828f00f281f32f", "C:\Users\ASADI\AppData\Local\Temp\jl_NsBHhEfP2
O-download.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
Downloading artifact: OpenSpecFun
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.
SecurityProtocolType" due to invalid enumeration values. Specify one of the fol
lowing enumeration values and try again. The possible enumeration values are "S
sl3, Tls"."
At line:1 char:35
+ [System.Net.ServicePointManager]:: <<<< SecurityProtocol =
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

Exception calling "DownloadFile" with "2" argument(s): "The underlying connecti
on was closed: An unexpected error occurred on a send."
At line:7 char:24
+ $webclient.DownloadFile <<<< ("https://github.com/JuliaBinaryWrappers/OpenSpe
cFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+3/OpenSpecFun.v0.5.3.x86_64-w6
4-mingw32-libgfortran5.tar.gz", "C:\Users\ASADI\AppData\Local\Temp\jl_g5JQbhrxA
O-download.gz")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
ERROR: Unable to automatically install 'OpenSpecFun' from 'C:\Users\ASADI\.julia
\packages\OpenSpecFun_jll\Xw8XK\Artifacts.toml'
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] ensure_artifact_installed(::String, ::Dict{String,Any}, ::String; platform:
:Pkg.BinaryPlatforms.Platform, verbose::Bool, quiet_download::Bool) at C:\buildb
ot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Artifacts.jl:8
99
 [3] ensure_all_artifacts_installed(::String; platform::Pkg.BinaryPlatforms.Plat
form, pkg_uuid::Nothing, include_lazy::Bool, verbose::Bool, quiet_download::Bool
) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\
Artifacts.jl:963
 [4] download_artifacts(::Pkg.Types.Context, ::Array{String,1}; platform::Pkg.Bi
naryPlatforms.Windows, verbose::Bool) at C:\buildbot\worker\package_win64\build\
usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:663
 [5] download_artifacts(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; p
latform::Pkg.BinaryPlatforms.Windows, verbose::Bool) at C:\buildbot\worker\packa
ge_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:642
 [6] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Array{Base.UUI
D,1}; preserve::Pkg.Types.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows)
at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Op
erations.jl:1141
 [7] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}; preserve::Pkg.Ty
pes.PreserveLevel, platform::Pkg.BinaryPlatforms.Windows, kwargs::Base.Iterators
.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\buildbot\worker\pa
ckage_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\API.jl:188
 [8] add(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at C:\buildbot\w
orker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\API.jl:139
 [9] #add#21 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1
.5\Pkg\src\API.jl:67 [inlined]
 [10] add at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\
Pkg\src\API.jl:67 [inlined]
 [11] #add#20 at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v
1.5\Pkg\src\API.jl:66 [inlined]
 [12] add at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\
Pkg\src\API.jl:66 [inlined]
 [13] add(::String; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTu
ple{(),Tuple{}}}) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdl
ib\v1.5\Pkg\src\API.jl:65
 [14] add(::String) at C:\buildbot\worker\package_win64\build\usr\share\julia\st
dlib\v1.5\Pkg\src\API.jl:65
 [15] top-level scope at REPL[4]:1

julia>

**Comment by Non-Contradiction** [comment]
@AsadiMarziehAF 
I have no idea about it and didn't have this problem before. The thing seems to be some internet setting thing which is beyond my expertise. But I think the best way to move this forward is to open a new issue for BinaryBuilder and describe your issue with error message from `import Pkg; Pkg.add("RCall")` or `import Pkg; Pkg.add("OpenSpecFun_jll") `.

**Comment by AsadiMarziehAF** [comment]
Hi, Changcheng Li
Thank you so much for the reply.

**Comment by AsadiMarziehAF** [comment]
Hi, Changcheng Li
Finally, I found my problem. My windows had a problem and didn't allow Julia to download the packages from the GitHub website. I installed "PowerShell 3" and the update for windows, then I could install packages in Julia and connect Julia and RStudio. 
Thank you so much
Marzieh

**Comment by Non-Contradiction** [comment]
@AsadiMarziehAF Great!

**Comment by Lili-619** [comment]
Hi No contradicción

This happend with me:   julia> ENV["R_HOME"] = "C:/Users/mictl/R/R-4.3.1"
"C:/Users/mictl/R/R-4.3.1"

julia> Base.include(Main,"C:/Users/mictl/R/R-4.3.1/library/JuliaCall/julia/setup.jl")
ERROR: LoadError: syntax: Global method definition around C:\Users\mictl\R\R-4.3.1\library\JuliaCall\julia\JuliaObject.jl:77 needs to be placed at the top level, or use "eval".
Stacktrace:
 [1] top-level scope
   @ C:\Users\mictl\R\R-4.3.1\library\JuliaCall\julia\JuliaObject.jl:75
 [2] include(mod::Module, _path::String)
   @ Base .\Base.jl:457
 [3] include(x::String)
   @ Main.JuliaCall C:\Users\mictl\R\R-4.3.1\library\JuliaCall\julia\setup.jl:16
 [4] top-level scope
   @ C:\Users\mictl\R\R-4.3.1\library\JuliaCall\julia\setup.jl:99
 [5] include(mod::Module, _path::String)
   @ Base .\Base.jl:457
 [6] top-level scope
   @ REPL[2]:1
in expression starting at C:\Users\mictl\R\R-4.3.1\library\JuliaCall\julia\JuliaObject.jl:75
in expression starting at C:\Users\mictl\R\R-4.3.1\library\JuliaCall\julia\setup.jl:16

**Comment by Faraz564** [comment]
Same issue with me after I follow the procedure to chang the path..

**Comment by Lili-619** [comment]
> ..

And... what happened? Does the program work?
If it is positive, could you tell me step by step how you did it?

**Comment by Faraz564** [comment]
I still have this problem. Julia_Setup is not run on my system since a month.

**Comment by Shafique313** [comment]
> Hey, I need to specify the full path to the Julia software on my computer and connect Julia to R. but I have been getting errors. The following text is the code that I used and the problem that occurred. Does anybody know how can I fix that? Thank you so much Marzieh
> 
> ```
> setwd("C:/Users/ASADI/Desktop/R")
> library(ResistanceGA)
> Loading required package: raster
> Loading required package: sp
> Registered S3 method overwritten by 'spatstat':
> method from
> print.boxx cli
> Warning message:
> replacing previous import ‘lme4::getData’ by ‘raster::getData’ when loading ‘ResistanceGA’
> JULIA_HOME <- "C:/Users/ASADI/AppData/Local/Julia-1.3.1/bin/"
> JuliaCall::julia_setup(JULIA_HOME)
> Julia version 1.3.1 at location C:\Users\ASADI\AppData\Local\JULIA-1.1\bin will be used.
> Loading setup script for JuliaCall...
> Error in .julia$cmd(paste0("Base.include(Main,"", system.file("julia/setup.jl", :
> Error happens when you try to execute command Base.include(Main,"C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/setup.jl") in Julia.
> To have more helpful error messages,
> you could considering running the command in Julia directly
> In addition: Warning message:
> In system2(file.path(.julia$bin_dir, "julia"), shQuote(command), :
> running command '"C:\Users\ASADI\AppData\Local\JULIA-1.1\bin/julia" "--startup-file=no" "C:/Users/ASADI/Documents/R/win-library/4.0/JuliaCall/julia/install_dependency.jl" "C:/PROGRA1/R/R-401.3"' had status 1
> Untitled
> ```
> 
> ![1](https://user-images.githubusercontent.com/57016053/107678404-9a145600-6cb0-11eb-90bd-d8c087a21c79.png)

Hi, Do you resolve this error? If yes please share the commands Thank You
