### ISSUE TITLE
when using JuliaCall in R: Error in inDL (x, as.logical(local), as.logical(now), ...) : character argument expected

### ISSUE THREAD

**Issue by zhaotianjing** [Non-Contradiction/JuliaCall#63]
- Background

I'm using `R version 3.5.1 (2018-07-02)`,  where the `R.exe` is in `C:\Program Files\R\R-3.5.1\bin`
and `Julia Version 0.7.0`, where `julia.exe` is in `C:\Users\carol\AppData\Local\Julia-0.7.0\bin`

I download the JuliaCall using `install.packages("JuliaCall")`, library location is `C:/Users/carol/Documents/R/win-library/3.5`

- Issue
In R:
`julia <- julia_setup()`   or 
`julia <- julia_setup(JULIA_HOME = "C:\\Users\\carol\\AppData\\Local\\Julia-0.7.0\\bin")`
it shows:
`Julia version 0.7.0 at location C:\Users\carol\AppData\Local\JULIA-~2.0\bin will be used.
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  character argument expected` (JULIA-~2.0 equals Julia-0.7.0)

- Note
`library(JuliaCall)` works fine;
I can use other library (eg. ggplot2) without error above. 

Do I need to add some **path** in System variables/user variables?
Can someone tell me what's wrong? thanks!

**Comment by Non-Contradiction** [comment]
The error message looks quite strange, because JuliaCall says:
```
Julia version 0.7.0 at location C:\Users\carol\AppData\Local\JULIA-~2.0\bin
```
And the location doesn't look right and it also doesn't match what you provided, which is `JULIA_HOME = "C:\\Users\\carol\\AppData\\Local\\Julia-0.7.0\\bin"`.
If this is really what the error message is, then I think it is the reason for the problem. 
But I'm not sure what caused this currently.

BtW, what is the version of JuliaCall you are using?

**Comment by zhaotianjing** [comment]
My JuliaCall version is `0.15.0`

**Comment by Non-Contradiction** [comment]
Okay, thanks for the clarification. The short form and long form of the filename on windows system sometimes is confusing...

I seem to find where the problem is, could you open a fresh julia v0.7 session and try the following: `print(Libdl.dlpath(Base.libm_name))`

And then open another fresh julia v0.7 session and try
`using Libdl; print(Libdl.dlpath(Base.libm_name))`

If the first one issues a warning, then this is where the problem is.
If the second one gives a filename without warning, then it should be the fix. 
And I can make a fix in the master quickly.

**Comment by zhaotianjing** [comment]
- For the first one:
`WARNING: Base.Libdl is deprecated, run `using Libdl` instead
 in module Main
C:\Users\carol\AppData\Local\Julia-0.7.0\bin\libopenlibm.DLL`

- For the second one in new session:
`WARNING: Base.Libdl is deprecated, run `using Libdl` instead
 in module Main
C:\Users\carol\AppData\Local\Julia-0.7.0\bin\libopenlibm.DLL`

**Same** warning
Could you please tell me how to fix it?  Thanks :)

**Comment by zhaotianjing** [comment]
Hi! @Non-Contradiction, thanks for your update.  
I update the package, but the problem still exist.

To prove it's the newest version:
`> devtools::install_github("Non-Contradiction/JuliaCall")`
`Skipping install of 'JuliaCall' from a github remote, the SHA1 (0fd5d609) has not changed since last install.
  Use `force = TRUE` to force installation`

**Comment by Non-Contradiction** [comment]
The error message is not very helpful.
How about trace the library load procedure before `julia_setup()`?
Just do `trace(dyn.load, quote(print(x)))` before `julia_setup()`.
So we can at least get some idea of what is going wrong.

**Comment by Non-Contradiction** [comment]
There is also a stack overflow question on the same topic: <https://stackoverflow.com/questions/51842129/julia-in-r-juliacall-and-xrjulia-not-working-with-julia-0-7-or-newer/>

**Comment by zhaotianjing** [comment]
Thanks for your update.
I update the library, but my R session aborted when running "julia <- julia_setup()"

**Comment by zhaotianjing** [comment]
The dll location is : `C:\\Users\\carol\\AppData\\Local\\Julia-0.7.0\\bin\\libopenlibm.DLL`
In R:  I run `dyn.load("C:\\Users\\ztjsw\\AppData\\Local\\Julia-0.7.0\\bin\\libopenlibm.DLL")` 
and then `julia <- julia_setup()`
The R session still aborted.

**Comment by Non-Contradiction** [comment]
Thank you for providing feedback.
Could you check whether it is the same case for `julia_setup()` in command line R without the `dyn.load`?

**Comment by zhaotianjing** [comment]
![image](https://user-images.githubusercontent.com/18593116/44113806-268de60e-9fbe-11e8-9046-1770efeb6c41.png)

still aborted

**Comment by Non-Contradiction** [comment]
My meaning is not using RStudio...but in command line / terminal.

Oh, BTW, what is the result of `using Pkg; Pkg.installed()["RCall"]` in julia?

**Comment by zhaotianjing** [comment]
Sorry,
In command line for `julia_setup():`
`Julia version 0.7.0 at location C:\Users\carol\AppData\Local\JULIA-~2.0\bin will be used.
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/carol/AppData/Local/JULIA-~2.0/bin/libopenlibm.DLL':
  LoadLibrary failure:  %1 is not a valid Win32 application.`

In Julia:
![image](https://user-images.githubusercontent.com/18593116/44114201-5fbbc684-9fbf-11e8-931a-017e67a32df3.png)

**Comment by Non-Contradiction** [comment]
Okay. Then the problem seems like a 32bit and 64bit problem.
R windows (from CRAN) carries both 32bit and 64bit of R. Which one are you using? From the error message, it seems that you are using 32bit R. Is this correct? And are you using 64bit Julia?
And you can't use 32bit R with 64bit Julia or 64bit R with 32bit Julia, because JuliaCall embeds Julia in R.

**Comment by zhaotianjing** [comment]
I checked my Julia is 64bit
and the R studio is using R 64bit in default
The R still aborted in R studio,

And if I run `julia_setup()` directly in R(64bit):
![image](https://user-images.githubusercontent.com/18593116/44115545-0d255698-9fc3-11e8-94cf-cb7a782c20bb.png)

It runs for about 10 min and still not stop...Is it normal?

**Comment by Non-Contradiction** [comment]
Yes, it is normal...
At the first time, the procedure can be quite looooong. Because JuliaCall needs to do some setting up like installing and precompiling Julia package dependencies. For example, Julia doesn't come with `DataFrames.jl` installed, which corresponds to R's `data.frame`, so JuliaCall needs to get that Julia package, and etc. After installation, it also needs to (pre)compile these packages (like compiling C code in R).
But after the first time, the startup time will be significantly faster because all the dependencies should be in place (for the current version of Julia).

**Comment by Non-Contradiction** [comment]
Does it stop now? 
JuliaCall should also prints out things like "Loading setup script for JuliaCall...", it it true?

**Comment by zhaotianjing** [comment]
Still running without `"Loading setup script for JuliaCall..."`
![image](https://user-images.githubusercontent.com/18593116/44118410-dae88b84-9fca-11e8-8f01-805b1ab956ec.png)

**Comment by zhaotianjing** [comment]
No, it still aborted. But if I add the 
`JuliaCall:::juliacall_initialize("C:\\Users\\carol\\AppData\\Local\\Julia-0.7.0\\bin\\libjulia.dll")`
Then everything works.

**Comment by Non-Contradiction** [comment]
Then it's really strange... Because in yesterday's test, the segfault is caused exactly by the invoke of `JuliaCall:::juliacall_initialize` in `julia_setup()` and everything happens before `JuliaCall:::julia_initialize` should be safe....

**Comment by Non-Contradiction** [comment]
I temporarily remove the only remaining thing happens before `JuliaCall:::juliacall_initialize` and might have interaction with `JuliaCall:::juliacall_initialize`. If it still segfault, then it is really really strange...

**Comment by zhaotianjing** [comment]
I update now, and it works without `JuliaCall:::juliacall_initialize(......)`

**Comment by Non-Contradiction** [comment]
Thanks for providing feedback!
Then it is `setwd()` to `JULIA_HOME` which causes segfault. 

Now `JuliaCall` should be fine with `Julia v0.7` and it should also work with `Julia v1.0` with the development version of `RCall`!

**Comment by zhaotianjing** [comment]
Thanks for @Non-Contradiction !

**Comment by Shafique313** [comment]
> Hi @Non-Contradiction , thanks for the update The dll location is : `C:\\Users\\carol\\AppData\\Local\\Julia-0.7.0\\bin\\libopenlibm.DLL` In R: I run `dyn.load("C:\\Users\\ztjsw\\AppData\\Local\\Julia-0.7.0\\bin\\libopenlibm.DLL")` and then `julia <- julia_setup()` The R session still aborted. ![image](https://user-images.githubusercontent.com/18593116/44112224-5b8e1536-9fb9-11e8-9948-5cc86b013fac.png)
> 
> BTW, in Julia ![image](https://user-images.githubusercontent.com/18593116/44113073-c434619c-9fbb-11e8-950c-eb0d7f52e096.png) but this works good: ![image](https://user-images.githubusercontent.com/18593116/44113165-0dcc18b8-9fbc-11e8-9aa6-b651613d7787.png) Maybe that's the reason for R aborted.

Hi Have you solved this error in your system? If yes please send m the commands, I am facing same issue with JuliaCall library, Thank You so much
