### ISSUE TITLE
Naming and visibility

### ISSUE THREAD

**Issue by Voltemand** [Non-Contradiction/JuliaCall#84]
I am sure that you are aware of the [Rjulia](https://github.com/armgong/rjulia) package which also provides a link between R and Julia. When you google `R Julia` the Rjulia package features prominently in the search results and appears pretty authoritative (until you dig into the lack of recent activity on Github). On the hand, the name **JuliaCall** while descriptive does make your package a bit hard to find.  I did notice that, for example, **JuliaCall** has about half as many stars on GitHub as Rjulia despite being a far better developed product. 

With all that in mind, have you ever considered getting permission from the creators of rjulia to use that name? I feel that would make it clear that JuliaCall is the number one Julia and R linking package and give it significantly more exposure. 

All the best!

**Comment by Non-Contradiction** [comment]
Thank you for the suggestion.
I guess different people see different google results? When I search `R Julia` with my google account logged in, I see two `JuliaCall` results in the first three, the GitHub repo and the CRAN page. And when I search without my google account on safari, I see the same two `JuliaCall` results in the first four. I also notice that when I type `R Julia`, one of Google's suggestion is `r juliacall`.
`JuliaCall` is a relatively young package compared to `RJulia`. When `JuliaCall` was developed (and I had no thought of turning `JuliaCall` into a full-featured interface between `R` and `Julia` at that time), I remembered that `RJulia` already had around 120 stars.

Since `JuliaCall` is already on CRAN and has some reverse dependencies here and there, there are both pros and cons for `JuliaCall` to change its name. Right now, I think it is better for `JuliaCall` to keep its name.
Thank you for the suggestion again.

**Comment by Voltemand** [comment]
Okay, thanks for considering - just an idea.
